name: Prepare docker images

on:
  workflow_dispatch:
    inputs:
      instance_set:
        description: "Instance set to solve"
        type: string

run-name: Prepare images (${{ inputs.instance_set }})

permissions:
  contents: read
  pull-requests: read
  packages: write

jobs:
  prepare_images:
    runs-on: SWE-Bench_Larger
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install virtualenv
          virtualenv venv
          . ./venv/bin/activate
          pip install -e .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare images
        env:
          INSTANCE_SET: ${{ inputs.instance_set }}
        run: |
          . ./venv/bin/activate
          instance_set="${INSTANCE_SET:-smoke}"
          python solver/prepare_images.py \
            --instance_set "${instance_set}"

      - name: Report image logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/build_images
          retention-days: 3
        
